### ISSUE TITLE
Error: Trying to override Model Schema when using: npm run test -- --watch

### ISSUE THREAD

**Issue by theclive** [sebelga/gstore-node#141]
Hi Guys,

We frequently use `npm run test -- --watch` to build tests.  This will watch project saves and run tests after each save.  When running the above command the tests all run and complete successfully, however on the first save I receive this error:

```
Error: Trying to override Campaign Model Schema
    at Gstore.model (/Users/Clive/Developer/addynamo/photomosaic-api/node_modules/gstore-node/lib/index.js:86:15)
    at Object.<anonymous> (/Users/Clive/Developer/addynamo/photomosaic-api/app/models/campaign.js:30:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Clive/Developer/addynamo/photomosaic-api/app/db/datastore.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Clive/Developer/addynamo/photomosaic-api/app/services/core/accept-image.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Clive/Developer/addynamo/photomosaic-api/app/services/core/index.js:1:87)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Clive/Developer/addynamo/photomosaic-api/app/services/index.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Clive/Developer/addynamo/photomosaic-api/app/router.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Clive/Developer/addynamo/photomosaic-api/app/app.js:26:34)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Clive/Developer/addynamo/photomosaic-api/test/services/core/accept-image.test.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/Clive/Developer/addynamo/photomosaic-api/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/Clive/Developer/addynamo/photomosaic-api/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/Clive/Developer/addynamo/photomosaic-api/node_modules/mocha/lib/mocha.js:576:10)
    at loadAndRun (/Users/Clive/Developer/addynamo/photomosaic-api/node_modules/mocha/bin/_mocha:594:22)
    at rerun (/Users/Clive/Developer/addynamo/photomosaic-api/node_modules/mocha/bin/_mocha:622:5)
    at utils.watch (/Users/Clive/Developer/addynamo/photomosaic-api/node_modules/mocha/bin/_mocha:630:7)
    at StatWatcher.<anonymous> (/Users/Clive/Developer/addynamo/photomosaic-api/node_modules/mocha/lib/utils.js:62:9)
    at StatWatcher.emit (events.js:182:13)
    at StatWatcher.onchange (internal/fs/watchers.js:50:8)
```

This occurs on the following line and throws before any tests are executed (i.e. when I "require" my datastore.js file, which requires the campaign.js schema file).

The code that it errors on is:

```
const Campaign = gstore.model('Campaign', schema)
```

I could not understand why this was throwing an exception because the schema (which is declared directly above it) is not changing, so why would it be trying to override the schema?

**My schema file for reference:**

```
const gstore = require('gstore-node')()
const Schema = gstore.Schema

const schema = new Schema({
  name: {
    type: String,
    required: true,
    excludeFromIndexes: true
  },

  imageUrl: {
    type: String,
    required: true,
    excludeFromIndexes: true
  },

  layers: {
    type: Number,
    required: true,
    excludeFromIndexes: true
  },

  duplication: {
    type: Number,
    required: true,
    excludeFromIndexes: true
  }
})

const Campaign = gstore.model('Campaign', schema)

module.exports = Campaign
```

I delved into the gstore-node code a bit and found the exception to be thrown on `index.js:79` which runs some code to double check if the schema has changed.  For reference here it is:

```
if (this.models[entityKind] && options.cache !== false) {
    if (schema && schema.instanceOfSchema && schema !== this.models[entityKind].schema) {
        throw new Error('Trying to override ' + entityKind + ' Model Schema');
    }
    return this.models[entityKind];
}
```

I used console.log to see what's going on and the issue seems to come in here: `schema !== this.models[entityKind].schema`  They differ by 1x key '__meta' and I can't figure out where it is coming from.

for reference, here are the two schema structures:

**schema**
```
{
  instanceOfSchema: true,
  methods: {},
  statics: {},
  virtuals: {},
  shortcutQueries: {},
  paths:
   { name:
      { type: [Function: String],
        required: true,
        excludeFromIndexes: true },
     imageUrl:
      { type: [Function: String],
        required: true,
        excludeFromIndexes: true },
     layers:
      { type: [Function: Number],
        required: true,
        excludeFromIndexes: true },
     duplication:
      { type: [Function: Number],
        required: true,
        excludeFromIndexes: true } },
  callQueue: { model: {}, entity: {} },
  options:
   { validateBeforeSave: true,
     queries: { readAll: false, format: 'JSON' } },
  __meta: {} }
```

**this.models[entityKind].schema**
```
{
  instanceOfSchema: true,
  methods: {},
  statics: {},
  virtuals: {},
  shortcutQueries: {},
  paths:
   { name:
      { type: [Function: String],
        required: true,
        excludeFromIndexes: true },
     imageUrl:
      { type: [Function: String],
        required: true,
        excludeFromIndexes: true },
     layers:
      { type: [Function: Number],
        required: true,
        excludeFromIndexes: true },
     duplication:
      { type: [Function: Number],
        required: true,
        excludeFromIndexes: true } },
  callQueue: { model: {}, entity: {} },
  options:
   { validateBeforeSave: true,
     queries: { readAll: false, format: 'JSON' } } }
```

**comparison**
![image](https://user-images.githubusercontent.com/23497305/51024208-89ed9200-1591-11e9-9682-913589123136.png)

I hope this is enough information for someone to help me figure this out?  I am not certain if the problem is my side or not.  Please help? and let me know if there is anything more you need from me to help debug?

**Comment by sebelga** [comment]
Hello,
You get this error because you define multiple times in your tests the same model. What you need to do is reset gstore models and schemas before each test  with:

```js
gstore.models = {};
gstore.modelSchemas = {};
```

Have a look at https://github.com/sebelga/gstore-node/blob/master/test/model-test.js#L32

Let me know if it solved the issue.
Cheers

**Comment by sebelga** [comment]
I will close this issue for no activity. Feel free to reopen if you still have the problem.
