### ISSUE TITLE
How to batch save operation?

### ISSUE THREAD

**Issue by Quinton** [sebelga/gstore-node#150]
- gstore-node version: 5.0.1

- model:
```javascript
'use strict';

const { instances } = require('gstore-node');
const gstore = instances.get('transport-unique-id');
const { Schema } = gstore;

/**
 * Create the schema for the City Model
 */
const cityInfoSchema = new Schema({
  code: { type: Number, required: true },
  name: { type: String, required: true },
  pinyin: { type: String, required: true },
});

const listQueryOptions = {
  limit: 1000,
};

// Configure "list" shortcut Query
cityInfoSchema.queries('list', listQueryOptions);

module.exports = gstore.model('CityInfo', cityInfoSchema);

```

- handler:
```javascript
exports.get = async () => {
  const cityInfoDiff = [{ code: 511300, name: '南充', pinyin: 'nan chong' }, { code: 440900, name: '茂名', pinyin: 'mao ming' }];
  const cityInfo = new CityInfo(cityInfoDiff);
  console.log(await cityInfo.save());
};
```

- test error:
```javascript
get_city_info
       implement tests here:
     ValidationError: The entity data does not validate against the "CityInfo" Schema
      at Object.validate (node_modules/gstore-node/lib/helpers/validation.js:301:27)
      at ModelInstance.validate (node_modules/gstore-node/lib/entity.js:200:45)
      at validateEntityData (node_modules/gstore-node/lib/entity.js:109:30)
      at ModelInstance.save (node_modules/gstore-node/lib/entity.js:56:25)
      at Wrapped.exports.get [as handler] (amap/city_info.js:21:30)
      at Promise (node_modules/lambda-wrapper/index.js:45:38)
      at new Promise (<anonymous>)
      at Wrapped.runHandler (node_modules/lambda-wrapper/index.js:24:12)
      at Wrapped.run (node_modules/lambda-wrapper/index.js:99:17)
      at Context.it (test/get_city_info.js:16:20)
      at process.topLevelDomainCallback (domain.js:121:23)
```

**Comment by sebelga** [comment]
You probably want something like:

```
exports.get = async () => {
    const cityInfoDiff = [{ code: 511300, name: '南充', pinyin: 'nan chong' }, { code: 440900, name: '茂名', pinyin: 'mao ming' }];
    await Promise.all(cityInfoDiff.map(info => {
        const cityInfo = new CityInfo(info);
        return cityInfo.save();
    }))
  };
```

**Comment by Quinton** [comment]
Thank you for response.
What I want is saving multi entities in one time,  Just like [batch_operations](https://cloud.google.com/datastore/docs/concepts/entities#batch_operations)

```javascript
  const cityInfoDiff = [{ code: 511300, name: '南充', pinyin: 'nan chong' }, { code: 440900, name: '茂名', pinyin: 'mao ming' }];
  await gstore.ds.insert(cityInfoDiff.map(ci => {
    return {
       key: CityInfo.key(),
      data: ci 
   };
  }));
```

**Comment by sebelga** [comment]
Ah ok, then you need to use the `gstore.save()` method (https://sebloix.gitbook.io/gstore-node/gstore-methods/save)

```js
exports.get = async () => {
    const cityInfoDiff = [
        { code: 511300, name: '南充', pinyin: 'nan chong' },
        { code: 440900, name: '茂名', pinyin: 'mao ming' }
    ];
    const entities = cityInfoDiff.map(info => new CityInfo(info));
    await gstore.save(entities, null, { validate: true, method: 'insert' })
  };
```

**Comment by Quinton** [comment]
thanx.
