### ISSUE TITLE
Update method doesn't clear cache

### ISSUE THREAD

**Issue by oander11** [sebelga/gstore-node#244]
Hi, 
I'm not sure if this is an issue or just a bit vagueness in the documentation but I think it's an issue :-)
I'm using gstore-node with a Redis cache (from GCP Memorystore) and I notice that if I do 
User.get(id) to get a user entity into the cache, and then do User.update(id, data) the cache is not cleared and the original, unmodified user is still there. 

I assume this is caused by the update method actually consists of two DB calls in a transaction, but I think that even if a general transaction operation must be manually managed wrt the cache, the update method should be able to support caching by itself? 

If not, and if the current behaviour is actually expected, maybe the documentation should explicitly mention this for the update method and the following text in cache/transactions section could be clarified (since at least I thought "edit an entity" == update )

_**For the most part you don't have to worry about clearing the cache as gstore-node automatically does it for you each time you add/edit or delete an entity.**_ 

Thanks for a great module!

**Comment by carnun** [comment]
Thank you for the feedback @oander11 can you please add a code snippet so that we can recreate the issue?

**Comment by oander11** [comment]
(I leave out boilerplate code for express etc) but the essential code is provided below.
When I do the Provider.get I get an object in the Redis cache with a name like: gck:1896000573. Since my first mail I have tried to manually clear the cache (see the commented rows in the code below) but I can't get those to work either. In the case where I get an exception (using clearCache with an id) the exception is:
```
TypeError: Cannot read property 'join' of undefined
    at keyToString (/Users/olaepspot/code/infrastructure-service/node_modules/nsql-cache-datastore/lib/index.js:99:29)
    at Object._db.keyToString.key [as keyToString] (/Users/olaepspot/code/infrastructure-service/node_modules/nsql-cache/lib/index.js:171:61)
    at keyToString (/Users/olaepspot/code/infrastructure-service/node_modules/nsql-cache/lib/keys.js:17:60)
    at cache.del.keys.map.k (/Users/olaepspot/code/infrastructure-service/node_modules/nsql-cache/lib/keys.js:208:54)
    at Array.map (<anonymous>)
    at Object.del (/Users/olaepspot/code/infrastructure-service/node_modules/nsql-cache/lib/keys.js:208:45)
    at Function.clearCache (/Users/olaepspot/code/infrastructure-service/node_modules/gstore-node/lib/model.js:357:58)
    at require.ProviderController.update (/Users/olaepspot/code/infrastructure-service/src/js/controllers/providerController.js:91:20)
```

 
### ProviderController.js 
```
ProviderController.get = async function (req, res) {
  try {
    let provider = await Provider.get(req.params.providerId);
    if (!provider) throw { code: 404, detailcode: 125, message: 'No such item.' };
    let jsonProvider = ModelService.processModel(req, provider); // just some basic processing of the data before returning
    res.send(jsonProvider);
  } catch (error) {
    RouteService.handleError(res, error);
  }
};

ProviderController.update = async function (req, res) {
  try {
    RoleService.verifyAccess(req, 'provider.update');
    let data = Provider.sanitize(req.body);
    console.log(data);
    let updatedEntity = await Provider.update(req.params.providerId, data);
    //await Provider.clearCache(); // this row has no effect
    //await Provider.clearCache(req.params.providerId); // this row causes exception in gstore-node
    let jsonEntity = ModelService.processModel(req, updatedEntity); // just some basic processing of the data 
    res.send(jsonEntity);
  } catch (error) {
    RouteService.handleError(res, error);
  }
};
```
### Initialization of cache etc
```
cache = new NsqlCache({
        db: dsAdapter(datastore),
        stores: [
        /*{
            store: 'memory',
            max: 200,
        },*/
        {
            store: redisStore,
            host: REDISHOST, 
            port: REDISPORT
        }],
        config: {
            ttl: {
                /*memory: {
                    keys: 20, // 20s
                    queries: -1, // do not store queries in memory since they may be stale
                },*/
                redis: {
                    keys: 60 * 60, //1h
                    queries: 60 * 60
                },
            }
        },
    });

let gstore = null;
if (cache) gstore = new Gstore({cache: cache, errorOnEntityNotFound: false});
else gstore = new Gstore({errorOnEntityNotFound: false});
gstore.connect(datastore);
```

**Comment by oander11** [comment]
Oops, forgot to include the Provider Model I use, in case that is relevant:

```
const {gstore}  = require('../util/storageService');
const { Schema } = gstore;
const validateAddress = require('./validation/validateAddress');
const validateContact = require('./validation/validateContact');

const providerSchema = new Schema({
  name: { type: String, required: true },
  invoiceEmail: { type: String, optional: true, validate: 'isEmail' },
  contact: { type: Object, optional: true, validate: { rule: validateContact }},
  supportContact: { type: Object, optional: true, validate: { rule: validateContact }},
  address: { type: Object, optional: true, validate: { rule: validateAddress }},
  imageAssets: { type: Array, optional: true }, // Array of Image Objects
  providerAdmin: { type: Object, optional: true, write: false, validate: { rule: validateContact }},
  createdOn: { type: Date, default: gstore.defaultValues.NOW, write: false, read: true},
  legacyId: { type: String, write: false, read: false },
});

let _x = gstore.model('V2Provider', providerSchema);

export const Provider = _x;
```

**Comment by carnun** [comment]
@oander11 is there any way you could reduce this to a basic model with gstore-node only code (e.g. without express.js controllers)? Getting everything (e.g. ./util/storageService, ./validation/*, etc) setup so that we can recreate this is going to take a lot of guesswork and probably doesn't relate to the actual issue.

Ideally something like:

```
const { Gstore } = require('gstore-node');
// setup cache - https://sebloix.gitbook.io/gstore-node/cache-dataloader/cache#default-configuration
const gstore = new Gstore({
    cache: {
        stores: [ ... ],
        config: { ... }
    },
});
// model setup
// steps of gstore calls which fail

```

Also have you looked into whether the issue is with gstore-node or with nsql-cache? This would be one of the first things we need to sort out.

**Comment by oander11** [comment]
Thanks for your help, by reducing the code to a very basic version I actually found the issue :-) Now all works according to expectation.
The issue was in the initialization of the cache. I earlier did:
```
let cache = new NsqlCache({
        db: dsAdapter(datastore),
        stores: [
        {
            store: redisStore,
            host: REDISHOST, 
            port: REDISPORT
        }],
        config: {
            ttl: {
                redis: {
                    keys: 60 * 60, 
                    queries: 60 * 60
                },
            }
        },
    });
```
Replacing the code above with the following code made it all work:
```
const cacheStores = [ {
    store: redisStore,
    host: REDISHOST, 
    port: REDISPORT, 
}];

const cacheConfig = {
    ttl: {
        redis: {
            keys: 60 * 60,
            queries: 60 * 60
        }
    }
};

let cache = {
        stores: cacheStores,
        config: cacheConfig
    };
```
(Why the first version doesn't work I haven't investigated)

**Comment by carnun** [comment]
@oander11 glad we could inadvertently help. I can't immediately tell why the one would work and the other not, but it you figure it out please let us know.
