### ISSUE TITLE
[help-wanted] Problem with save method: Saving doesn't do anything

### ISSUE THREAD

**Issue by digaresc** [sebelga/gstore-node#28]
Hi, 
I'm having some issues working with the library. Maybe I'm initializing in a bad way the gstore-node?

Saving is not working, or nothing happens at all when this method is executed:
```
    var data = ClientApp.sanitize(req.body);
    console.log(data);
    var clientApp = new ClientApp(data,data.appName);

    clientApp.save().then(function() {
        this.datastoreEntity().then((data) => {
            var entity = data[0];
            console.log(entity);
        });
    }).catch((err) => {
        console.log(err);
    });
```

Here are the files:
clientApp.controller.js
```
var ClientApp = require('../models/clientApp');

function create(req, res) {
    var data = ClientApp.sanitize(req.body);
    console.log(data);

    // {
    //     appName: 'Yikes',
    //     androidBundleId: 't.t.t',
    //     iosBundleId: 'a.a.a'
    // }

    var clientApp = new ClientApp(data, data.appName);

    var data = ClientApp.sanitize(req.body);
    console.log(data);
    var clientApp = new ClientApp(data,data.appName);

    clientApp.save().then(function() {
        this.datastoreEntity().then((data) => {
            var entity = data[0];
            console.log(entity);
        });
    }).catch((err) => {
        console.log(err);
    });
}


module.exports = {
    create: create
};

```
(Model)
clientApp.js

```
var uuid = require('uuid');

var datastore = require('@google-cloud/datastore')({
    projectId: 'tttttttt',
    keyFilename: './keyfile.json'
});

var gstore = require('gstore-node');
gstore.connect(datastore);

var Schema = gstore.Schema;

var schema = new Schema({
    appName: {
        type: 'string',
        required: true,
        read: false
    },
    androidBundleId: {
        type: 'string',
        required: true,
        read: false
    },
    iosBundleId: {
        type: 'string',
        required: true,
        read: false
    },
    modified: {
        type: 'boolean',
        default: false,
        read: false,
        write: false
    },
    createdOn: {
        type: 'datetime',
        default: gstore.defaultValues.NOW,
        write: false,
        read: false
    },
    appKey: {
        type: 'string',
        default: uuid.v4(),
        write: false
    }
});

schema.virtual('timestamp').get(function() {
    // the scope (this) is the entityData object
    return this.createdOn;
});

var ClientApp = gstore.model('ClientApp', schema);

module.exports = ClientApp;
```

**Comment by digaresc** [comment]
Updated to node v6.9.1 and now I get this error:

> Error: Property not allowed { undefined } for ClientApp Entity
>     at Object.keys.forEach (/Users/digaresc/Bridgefy/src/sdk-backend/node_modules/gstore-node/lib/model.js:879:37)
>     at Array.forEach (native)
>     at ModelInstance.validate (/Users/digaresc/Bridgefy/src/sdk-backend/node_modules/gstore-node/lib/model.js:856:38)
>     at Promise (/Users/digaresc/Bridgefy/src/sdk-backend/node_modules/gstore-node/lib/schema.js:60:23)
>     at ModelInstance.fn (/Users/digaresc/Bridgefy/src/sdk-backend/node_modules/gstore-node/lib/schema.js:58:20)
>     at ModelInstance.next (/Users/digaresc/Bridgefy/src/sdk-backend/node_modules/promised-hooks/hooks.js:109:44)
>     at Promise (/Users/digaresc/Bridgefy/src/sdk-backend/node_modules/promised-hooks/hooks.js:116:29)
>     at ModelInstance.wrapper [as save] (/Users/digaresc/Bridgefy/src/sdk-backend/node_modules/promised-hooks/hooks.js:71:20)
>     at create (/Users/digaresc/Bridgefy/src/sdk-backend/controllers/clientApp.controller.js:19:15)
>     at Layer.handle [as handle_request] (/Users/digaresc/Bridgefy/src/sdk-backend/node_modules/express/lib/router/layer.js:95:5)

**Comment by sebelga** [comment]
Hi,
I can't spot the error so let me write how it "should" work and see from there.
You need node > 4 (so 6.9.1 is perfect)

```js
// server.js
// This is your main starting file
var datastore = require('@google-cloud/datastore')({
    projectId: 'tttttttt',
    keyFilename: './keyfile.json'
});

var gstore = require('gstore-node');
gstore.connect(datastore);

// ... rest of your initial setup
```

```js
// client-app.model.js

var gstore = require('gstore-node');
var uuid = require('uuid');
var Schema = gstore.Schema;

var schema = new Schema({
    appName: {
        type: 'string',
        required: true,
        read: false
    },
    androidBundleId: {
        type: 'string',
        required: true,
        read: false
    },
    iosBundleId: {
        type: 'string',
        required: true,
        read: false
    },
    modified: {
        type: 'boolean',
        default: false,
        read: false,
        write: false
    },
    createdOn: {
        type: 'datetime',
        default: gstore.defaultValues.NOW,
        write: false,
        read: false
    },
    appKey: {
        type: 'string',
        default: uuid.v4(), // careful as this value will be "static" for all instance. I will add a fix to that soon
        write: false
    }
});

schema.virtual('timestamp').get(function() {
    // the scope (this) is the entityData object
    return this.createdOn;
});

var ClientAppModel = gstore.model('ClientApp', schema); // don't suffix "Model" to the entity kind.

module.exports = ClientAppModel;
```

```js
// client-app.controller.js
var ClientAppModel = require('../models/client-app.model.js');

function create(req, res) {
    var data = ClientAppModel.sanitize(req.body);
    var clientApp = new ClientAppModel(data, data.appName);
    delete data.appName; // You probably don't need it anymore as it is now the 'id'

    clientApp.save().then(function() {
        res.json(this.plain());
    }).catch((err) => {
        console.log(err);
        res.status(400).json(err);
    });
}

module.exports = {
    create: create
};

```

**Comment by digaresc** [comment]
Same problem.

Do you want me do do something else? 

If I do a:

`console.log(clientapp.entityData)`

I got this, isn't there something strange?

I have been following all the the steps.

 ```
{ appName: 'Yikes',
  androidBundleId: 'com.yikes.android',
  iosBundleId: 'com.yikes.ios',
  modified: false,
  createdOn: 2016-12-02T19:41:49.885Z,
  appKey: '51a22620-92b3-4c21-8125-0c6e7b3b98c0',
  undefined:
   Key {
     namespace: undefined,
     name: 'Yikes',
     kind: 'ClientApp',
     path: [Getter] } }
```

Thanks in advance.

**Comment by sebelga** [comment]
Where do you do this console.log? If you did it inside the resolve of the Promise, it means that it did work and the entity should be saved in the datastore.

**Comment by digaresc** [comment]
Found the problem. The problem was that I had installed an older version of google datastore and I installed on top gstore-node. After I removed the older version everything worked perfect.
Probably because I started with one of the GoogleCloudPlatform/nodejs-docs-samples that had an older version. My bad.

Thanks for the fast support. 
Happy to help around here.

**Comment by sebelga** [comment]
Great, happy you found the solution.
